### ISSUE TITLE
Update language server, ensure backward/forward compatibility

### ISSUE THREAD

**Issue by PeyTy** [hexalang/hexa-vscode-bundle#2]
- [ ] Option to use constant TCP connection instead of REST (btw use this mode by default?)
- [ ] Handle in-compiler crash gracefully (this is done, refactor and commit)
- [ ] Sidebar outline improvements, take types from Typer when possible?
- [ ] Go to definition (Ctrl+Click) / Go to type definition
- [ ] Ensure backward/forward compatibility
  - [ ] FP-style table of callbacks for kinds of lint reports (for things like hints, in future)
- [ ] Highlight words, operators and blocks properly
- [ ] More info on hover (var type & mutability, optimization opportunities, etc)
- [ ] Refactoring features (like rename class/etc, warn about name clashes (global and within one file cause aliases))
- [ ] Fix underline positions (use spans)
- [ ] Find all refs
- [ ] Dim unused
- [ ] Other common LSP features to this list
- [ ] Update snippets
- [ ] Shallow type check (i.e. don't stop after some type errors)
- [ ] Better cache
- [ ] Dim unreachable code
- [ ] Stop type check when desired lint info is reached (optimization)
- [ ] Autorun Hexa server
- [ ] Inline dimmed inferred types
  - [ ] `for i TYPE in e`
  - [ ] `var v TYPE` `let v TYPE`
  - [ ] Option to disable this
- [ ] Lint of unsaved file
  - [ ] Project-related
  - [ ] Independent
- [ ] Autocomplete improvements
  - [ ] Local vars/funcs in current block
  - [ ] `: Type`
  - [ ] Fields `.HERE`
  - [ ] Option to insert colons for arg names `func(name:, name:)` also always show them in autocomplete list
