### ISSUE TITLE
Upload to store next release

### ISSUE THREAD

**Issue by PeyTy** [hexalang/hexa-vscode-bundle#3]
- [ ] README
  - [ ] add some screenshots and features list
  - [ ] add command `code --how-to-install-from-cli` example
- [ ] Hexa path and PATH
- [ ] Option to disable inline error reporting
   - [ ] Fix color of the inline error reporting (brighter red, generate from theme?)
- [ ] Option to set linting delay
- [ ] Open VSX Registry
- [x] Rename branch to kawaii and update protection rules
